### ISSUE TITLE
Agents in dungeons

### ISSUE THREAD

**Issue by shibeinu** [SecretFox/AgentSwitcher#1]
There are several encounters in The Darkness War where you engage with trash mobs before boss. Is there a way to automatically choose the agent based on boss instead of the first mob you target? Maybe based on the tier on dungeon mission?

**Comment by MakeMods** [comment]
Tier wasn't quite reliable enough, it didn't seem to always update for each boss,and was also limited to dungeons.
I added proximity/kill based switching in the latest release, default settings should be pretty good for dungeons.
