### ISSUE TITLE
Disable switching while tanking?

### ISSUE THREAD

**Issue by Darxide23** [SecretFox/AgentSwitcher#2]
Is there an option to automatically disable switching while tanking? There's never a case where having a +weapon% agent is better than a +Attack Rating agent for purposes of aggro while tanking. I've been manually switching off the addon, but I often forget or forget to turn it back on. I don't know where the Attack Rating cutoff is, but I would assume anything >50% survival that you are considered to be tanking.

**Comment by MakeMods** [comment]
I'll see if i can add it without further spaghettifying my code
