### ISSUE TITLE
The MoD is not working for me 

### ISSUE THREAD

**Issue by Ascarys** [SecretFox/AgentSwitcher#3]
Hi, for some reason this MoD is not working for me, all others MODs are absolutley fine.
Do i have to install some other MOD in order for this one to work ? Do i have to do something in the game settings ? I am playing from Steam and the MOD is installed to Steam->Steamapps->Common->SecretWorldLegends->Data->Gui->Custom->Flash.

Thank you

**Comment by MakeMods** [comment]
Hello
Sorry for late response.
No other mods needed and the install location appears correct.  

Make sure you are downloading the `AgentSwitcher-vX.X.X.zip` https://github.com/SecretFox/AgentSwitcher/releases and not the source code.zip.
After extracting the contents .swf file location should be `"Secret World Legends\Data\Gui\Custom\Flash\AgentSwitcher\AgentSwitcher.swf"`
Also make sure that there are no extra copies of the mod in any other folder,as they can prevent the mod from loading.

You can also type `/option AgentSwitcher` in chat, which should print out `Variable <AgentSwitcher> is <true>` if the game recognizes that the mod is installed.
Mod icons default position should be little under the topbar currency.

**Comment by Ascarys** [comment]
Now it`s working, i`ve must have been download wrong one previous time, thank you alot
